---

- name: install sudo
  package:
    name: ["sudo"]
    state: present

- name: sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: set sudo configuration
  template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"

- name: enable ssh pipelining
  set_fact:
    ansible_ssh_pipelining: true
